app = 'zip-zap-zop'
primary_region = 'hkg'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'

[[statics]]
url_prefix = '/'
guest_path = '/game'
